vm_name = "testvm123"
datastore = "test"
esxi_host = ""
network_name = "" 
vcenter_server = ""
vcenter_username = "Administrator@vsphere.local" 
vcenter_password = "" 
ssh_username = "root"
ssh_password = "password" 

