vm_name = "testvm123"
datastore = "Datastore"
esxi_host = ""
network_name = "" 
vcenter_server = ""
vcenter_username = "Administrator@vsphere.local" 
vcenter_password = "" 
ssh_username = "labuser"
ssh_password = "labuser" 

